import { StyleSheet } from '@react-pdf/renderer';

export const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: 'Helvetica',
    fontSize: 10,
    color: '#333333',
    backgroundColor: '#FFFFFF',
  },
  headerContainer: {
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#EEEEEE',
    paddingBottom: 10,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  companyInfo: {
    width: '55%',
  },
  companyName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#3D2314', // Chocolate brown
    marginBottom: 4,
  },
  companyDetails: {
    fontSize: 9,
    color: '#666666',
    lineHeight: 1.4,
  },
  ledgerInfo: {
    width: '45%',
    alignItems: 'flex-end',
  },
  ledgerTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#3D2314',
    marginBottom: 4,
    textAlign: 'right',
  },
  ledgerDates: {
    fontSize: 9,
    color: '#666666',
    lineHeight: 1.4,
    textAlign: 'right',
  },
  table: {
    display: 'flex',
    width: 'auto',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#EEEEEE',
    borderRightWidth: 0,
    borderBottomWidth: 0,
  },
  tableRow: {
    margin: 'auto',
    flexDirection: 'row',
  },
  tableHeaderRow: {
    backgroundColor: '#F9E9B9', // Butter Yellow
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#EEEEEE',
  },
  tableColDate: {
    width: '12%',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#EEEEEE',
    borderLeftWidth: 0,
    borderTopWidth: 0,
  },
  tableColParticulars: {
    width: '38%',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#EEEEEE',
    borderLeftWidth: 0,
    borderTopWidth: 0,
  },
  tableColVchType: {
    width: '10%',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#EEEEEE',
    borderLeftWidth: 0,
    borderTopWidth: 0,
  },
  tableColVchNo: {
    width: '10%',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#EEEEEE',
    borderLeftWidth: 0,
    borderTopWidth: 0,
  },
  tableColAmount: {
    width: '15%',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#EEEEEE',
    borderLeftWidth: 0,
    borderTopWidth: 0,
  },
  tableCellHeader: {
    margin: 5,
    fontSize: 9,
    fontWeight: 'bold',
    color: '#3D2314',
  },
  tableCell: {
    margin: 5,
    fontSize: 9,
  },
  tableCellRight: {
    margin: 5,
    fontSize: 9,
    textAlign: 'right',
  },
  tableCellHeaderRight: {
    margin: 5,
    fontSize: 9,
    fontWeight: 'bold',
    color: '#3D2314',
    textAlign: 'right',
  },
  totalsRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#EEEEEE',
    backgroundColor: '#FAFAFA',
  },
  totalsLabel: {
    width: '70%',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#EEEEEE',
    borderLeftWidth: 0,
    borderTopWidth: 0,
    padding: 5,
    textAlign: 'right',
    fontSize: 9,
    fontWeight: 'bold',
    color: '#3D2314',
  },
  balanceRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#EEEEEE',
    backgroundColor: '#FDFBF7', // Cream
  },
  emptyState: {
    padding: 20,
    textAlign: 'center',
    fontSize: 10,
    color: '#666666',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#EEEEEE',
    borderTopWidth: 0,
  },
  footer: {
    position: 'absolute',
    bottom: 20,
    left: 40,
    right: 40,
    fontSize: 8,
    color: '#999999',
    textAlign: 'center',
    borderTopWidth: 1,
    borderTopColor: '#EEEEEE',
    paddingTop: 10,
  },
});
